---
# tasks file for apache
- name: install httpd package
  ansible.builtin.yum:
    name: httpd
    state: present
- name: start and enable httpd
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started
- name: install firewall package
  ansible.builtin.yum:
    name: firewalld
    state: present
- name: start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started
- name: allow http in firewall rule
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled 
- name: add content
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
  notify: restart httpd

