---
- name: gather facts from prod
  hosts: all
  gather_facts: yes
  become: true
  
- name: deploy balancer role
  hosts: balancers
  become: true
  roles:
    - balancer

- name: deploy phpinfo role
  hosts: webservers
  become: true
  roles:
    - phpinfo

