---
- name: Create yum repository in all machines
  hosts: all
  tasks:
    - name: create EX294_BASE repository
      ansible.builtin.yum_repository:    
        name: BaseOS
        file: yum
        description: EX294 base software
        enabled: yes
        baseurl: http://repo.example.com
        gpgcheck: yes
        ggpkey: http://repo.example.com/RPM-GPG-KEY

    - name: create EX294_APP repository
      ansible.builtin.yum_repository:
        name: AppStream 
        file: yum
        description: EX294 app software
        enabled: yes
        baseurl: http://repo.example.com
        gpgcheck: yes
        ggpkey: http://repo.example.com/RPM-GPG-KEY
